include: "rules/common.smk"


##### Target rules #####
localrules: make_scaff_group_interval_lists, make_chromo_interval_lists, combine_bcftools_stats

rule all:
    input:
        #expand("results/genomics_db/chromosomes/{c}", c=chromosomes.chrom),
        #expand("results/genomics_db/scaffold_groups/{s}", s=unique_scaff_groups),
        #expand("results/vcf_sections/{c}.vcf.gz", c=chromosomes.chrom),
        #expand("results/vcf_sections/{s}.vcf.gz", s=unique_scaff_groups),
        "results/bcf/all.bcf",
        "results/bcf/all.bcf.csi",
        "results/qc/multiqc.html",
        expand("results/bcf/pass-maf-{maf}.bcf", maf=mafs),
        expand("results/qc/bcftools_stats/all-{fc}.txt", fc=["ALL", "PASS", "FAIL"]),
        expand("results/qc/bcftools_stats/all-pass-maf-{maf}.txt", maf=mafs)

rule old_all:
    input:
        "annotated/all.vcf.gz",
        "qc/multiqc.html",
        "plots/depths.svg",
        "plots/allele-freqs.svg",


##### Modules #####


include: "rules/ref.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/filtering.smk"
include: "rules/stats.smk"
include: "rules/qc.smk"
include: "rules/hardfilter.smk"
include: "rules/annotation.smk"
