include: "rules/common.smk"


##### Target rules #####


rule all:
    input:
        #expand("results/genomics_db/chromosomes/{c}", c=chromosomes.chrom),
        #expand("results/genomics_db/scaffold_groups/{s}", s=unique_scaff_groups),
        #expand("results/vcf_sections/{c}.vcf.gz", c=chromosomes.chrom),
        #expand("results/vcf_sections/{s}.vcf.gz", s=unique_scaff_groups),
        "results/vcf/all-filtered.vcf.gz",
        "results/vcf/all-filtered.vcf.gz.tbi",
        "results/qc/multiqc.html",
        expand("results/qc/bcftools_stats/bcftools-stats-{fc}.txt", fc=["ALL", "PASS", "FAIL"])

rule old_all:
    input:
        "annotated/all.vcf.gz",
        "qc/multiqc.html",
        "plots/depths.svg",
        "plots/allele-freqs.svg",


##### Modules #####


include: "rules/ref.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/filtering.smk"
include: "rules/stats.smk"
include: "rules/qc.smk"
include: "rules/gatk-hardfilter.smk"
include: "rules/annotation.smk"
