include: "rules/common.smk"


##### Target rules #####
localrules: make_scaff_group_interval_lists, make_chromo_interval_lists, combine_bcftools_stats

rule all:
    input:
        #expand("results/bqsr-round-{bq}/genomics_db/chromosomes/{c}", c=chromosomes.chrom),
        #expand("results/bqsr-round-{bq}/genomics_db/scaffold_groups/{s}", s=unique_scaff_groups),
        #expand("results/bqsr-round-{bq}/vcf_sections/{c}.vcf.gz", c=chromosomes.chrom),
        #expand("results/bqsr-round-{bq}/vcf_sections/{s}.vcf.gz", s=unique_scaff_groups),
        expand("results/bqsr-round-{bq}/bcf/all.bcf", bq=config["bqsr_rounds"]),
        expand("results/bqsr-round-{bq}/bcf/all.bcf.csi", bq=config["bqsr_rounds"]),
        expand("results/bqsr-round-{bq}/qc/multiqc.html", bq=config["bqsr_rounds"]),
        expand("results/bqsr-round-{bq}/bcf/pass-maf-{maf}.bcf", maf=mafs,  bq=config["bqsr_rounds"]),
        expand("results/bqsr-round-{bq}/qc/bcftools_stats/all-{fc}.txt", fc=["ALL", "PASS", "FAIL"],  bq=config["bqsr_rounds"]),
        expand("results/bqsr-round-{bq}/qc/bcftools_stats/all-pass-maf-{maf}.txt", maf=mafs,  bq=config["bqsr_rounds"]),

rule old_all:
    input:
        "annotated/all.vcf.gz",
        "qc/multiqc.html",
        "plots/depths.svg",
        "plots/allele-freqs.svg",


##### Modules #####


include: "rules/ref.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/filtering.smk"
include: "rules/stats.smk"
include: "rules/qc.smk"
include: "rules/hardfilter.smk"
include: "rules/annotation.smk"
